movement_steering:
  ros__parameters:
    # gesture names
    gestures: ["down", "up", "left", "right", "front", "back", "nothing"]
    
    # steering constants
    linear_y_const: 0.3
    linear_x_const: 0.3
    linear_z_const: 0.5
    angular_z_const: 1.0
    
    # model parameters
    confidence_threshold: 0.8

    # hand tracker parameters
    width: 640  # 960
    height: 480 # 720
    min_detection_confidence: 0.5
    min_tracking_confidence: 0.5
    draw: True